const isExpress = require("express");
const logger = require("morgan");
const bodyParser = require("body-parser");
const cookieParser = require("cookie-parser");
const userRouter = require("./router/userRouter");
const app  = isExpress();
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(isExpress.static(__dirname+"/public",{index:"login.html"}));
app.use(userRouter);
app.listen(9999);
